
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProvidersApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class payments
{

    public int id { get; set; }

    public System.DateTime date { get; set; }

    public int payment_value { get; set; }

    public int id_subscriber_tariff { get; set; }



    public virtual subscriber_tariff_list subscriber_tariff_list { get; set; }

}

}
