
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProvidersApp.Models
{

using System;
    using System.Collections.Generic;
    
public partial class personal_data
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public personal_data()
    {

        this.subscribers = new HashSet<subscribers>();

    }


    public int id { get; set; }

    public string address { get; set; }

    public string passport_info { get; set; }

    public System.DateTime birthday { get; set; }

    public string sex { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<subscribers> subscribers { get; set; }

}

}
