

//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ProvidersApp.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class providersEntities : DbContext
{
    public providersEntities()
        : base("name=providersEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<operators> operators { get; set; }

    public virtual DbSet<payments> payments { get; set; }

    public virtual DbSet<personal_data> personal_data { get; set; }

    public virtual DbSet<regions> regions { get; set; }

    public virtual DbSet<subscriber_tariff_list> subscriber_tariff_list { get; set; }

    public virtual DbSet<subscribers> subscribers { get; set; }

    public virtual DbSet<tariffs> tariffs { get; set; }

}

}

